mongodb:
  image: frodenas/mongodb
  ports:
    - 27018:27017
  environment:
    - MONGODB_USERNAME=dennis
    - MONGODB_PASSWORD=changeit
    - MONGODB_DBNAME=Employees
  volumes:
    - ./tmp/mongodb:/data
  command: --smallfiles --journal
